apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: arsam-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.176.200-192.168.176.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: arsam-advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - arsam-pool
